<?php declare(strict_types=1);

require_once __DIR__ . '/../../bootstrap.php';

/**
 * The logic of the class and its test is heavily inspired by Nette\DI\ContainerLoader.
 *
 * @see https://github.com/nette/di/blob/master/tests/DI/ContainerLoader.loadFile.phpt
 */

// delete remnants of previous runs
@unlink(TempDir . '/GeneratedClass.php');


$generatedClassLoader = new Vojtechdobes\GraphQL\GeneratedClassLoader();


$generatedClassName = GeneratedClass::class; // @phpstan-ignore class.notFound (This class is generated by this test)

$generatedClassLoader->generateAndLoadCachedClass(
	TempDir,
	$generatedClassName,
	static function ($className): Nette\PhpGenerator\PhpFile {
		$result = new Nette\PhpGenerator\PhpFile();
		$result->addClass($className);
		return $result;
	},
);

$classFile = new ReflectionClass($generatedClassName)->getFileName();
Tester\Assert::true(is_string($classFile) && is_file($classFile));


// avoid redeclaring the class on next include call
file_put_contents(TempDir . '/GeneratedClass.php', '');

$generatedClassLoader->generateAndLoadCachedClass(
	TempDir,
	$generatedClassName,
	static function (): never {
		Tester\Assert::fail("Regeneration shouldn't occur");
	},
);
